### ISSUE TITLE
Support String filed type for Date_Notion_name field

### ISSUE THREAD

**Issue by baramofme** [HUIXIN-TW/NotionSyncGCal#16]
I have formula field that show one of Date field value with if/else statement.

Expect behavior

Given 
There are "Do date", "Due date".
If "Do date" has a value, folmula field show date as string with formatDate function.
else show "Due date" value as string

When I execute Sync, 
Then, formula field string value(formated) will sync GCal properly.

Real behavior

Given
sams as up.

When I execute Sync,
Then, Got type not match error
"notion_client.errors.APIResponseError: The formula has a result type that does not match the property type of the filter provided: formula text does not match filter dat"

```
################################## START ##################################
###########################################################################
--- Run Sync.py | After 2023-09-07 Included, Before 2023-09-10 Not Included ---
Displaying output on the terminal...
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\notion_client\client.py", line 83, in _parse_response
    response.raise_for_status()
  File "C:\ProgramData\Anaconda3\lib\site-packages\httpx\_models.py", line 1105, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://api.notion.com/v1/databases/4c6e0dc9b84e45e08149ce42a709c885/query
For more information check: https://httpstatuses.com/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Jihoon\IdeaProjects\NotionSyncGCal\src\main.py", line 159, in <module>
    main()
  File "C:\Users\Jihoon\IdeaProjects\NotionSyncGCal\src\main.py", line 155, in main
    execute_sync_action(s, sys.argv)
  File "C:\Users\Jihoon\IdeaProjects\NotionSyncGCal\src\main.py", line 54, in execute_sync_action
    s.notion_to_gcal(action=0, updateEverything=True)
  File "C:\Users\Jihoon\IdeaProjects\NotionSyncGCal\src\Sync.py", line 727, in notion_to_gcal
    resultList = queryNotionEvent_notion()
  File "C:\Users\Jihoon\IdeaProjects\NotionSyncGCal\src\Sync.py", line 306, in queryNotionEvent_notion
    my_page = nt.NOTION.databases.query(
  File "C:\ProgramData\Anaconda3\lib\site-packages\notion_client\api_endpoints.py", line 46, in query
    return self.parent.request(
  File "C:\ProgramData\Anaconda3\lib\site-packages\notion_client\client.py", line 133, in request
    return self._parse_response(response)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notion_client\client.py", line 93, in _parse_response
    raise APIResponseError(error.response, body)
notion_client.errors.APIResponseError: The formula has a result type that does not match the property type of the filter provided: formula text does not match filter date
```

**Comment by HUIXIN-TW** [comment]
Hello,

Thank you for bringing this to my attention. It seems the issue is arising because the formula field is returning a text type, while the filter is expecting a date type.

As of now, it might be necessary to use a date property instead of a formula property, as they have different JSON structures and it might not be possible to modify it to a formula property. You can **retain the "Do Date" which returns date type** and **use another property for the formula** to run the Notion management console exclusively. I hope this solution works for you.

I appreciate your interest in my project and your help in identifying this issue. Please let me know if you have any further questions or suggestions.
